# Generated by Django 3.2.2 on 2021-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
    ]
