# Generated by Django 3.2.2 on 2021-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_accounts', '0002_auto_20210520_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:\\Users\\Lenovo\\Desktop\\proj\\picture', null=True, upload_to='profile/', verbose_name='تصویر'),
        ),
    ]
