# Generated by Django 3.2.2 on 2021-05-21 15:19

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_accounts', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=pathlib.PureWindowsPath('C:/Users/Lenovo/Desktop/abc/media/profile/4.jpg'), upload_to='profile/', verbose_name='تصویر'),
        ),
    ]
