# Generated by Django 3.2.3 on 2021-05-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20210519_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted']},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reactioninstance',
            options={},
        ),
    ]
