# Generated by Django 3.2.2 on 2021-05-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210519_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('access_product', 'access to CRUD of product')], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
