# Generated by Django 3.2.3 on 2021-05-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_accounts', '0003_auto_20210523_1729'),
        ('products', '0005_productsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='products.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suplier', to='eshop_accounts.suplier', verbose_name='تامین کننده'),
        ),
    ]
